import json
from typing import Optional


def save_founder_profile(
    technical_background: str,
    idea_description: str,
    idea_category: str,
    runway_months: int,
    has_budget: bool,
    has_shipped_product: bool,
    biggest_fear: str,
) -> dict:
    """
    Save the founder's profile to session state for use by later agents.
    Call this after extracting all information from the founder's interview answers.

    Args:
        technical_background: Their skills, languages, years of experience
        idea_description: 2-3 sentence description of the startup idea
        idea_category: One of: SaaS, Marketplace, AI Tool, Mobile App, Developer Tool, Consumer, Other
        runway_months: How many months they can work on this
        has_budget: Whether they have any financial budget
        has_shipped_product: Whether they have shipped a product before
        biggest_fear: Their stated biggest concern about pursuing this idea

    Returns:
        Confirmation dict with the saved profile summary
    """
    try:
        profile = {
            "technical_background": technical_background,
            "idea_description": idea_description,
            "idea_category": idea_category,
            "runway_months": runway_months,
            "has_budget": has_budget,
            "has_shipped_product": has_shipped_product,
            "biggest_fear": biggest_fear,
        }
        return {"status": "saved", "profile": profile, "message": "Founder profile captured successfully."}
    except Exception as e:
        return {"error": str(e), "status": "failed"}


def calculate_founder_fit_score(
    technical_score: int,
    execution_score: int,
    market_score: int,
    risk_adjusted_score: int,
    reasoning: str,
) -> dict:
    """
    Calculate and record the official Founder Fit Score.
    Call this after evaluating all four scoring dimensions.

    Args:
        technical_score: Score 0-25 for technical capability
        execution_score: Score 0-25 for execution ability
        market_score: Score 0-25 for market positioning
        risk_adjusted_score: Score 0-25 for risk-adjusted outlook
        reasoning: 2-3 sentence explanation of the overall score

    Returns:
        The final score object with breakdown
    """
    try:
        total = technical_score + execution_score + market_score + risk_adjusted_score
        total = max(0, min(100, total))  # clamp to 0-100

        if total >= 85:
            label = "Exceptional"
            color = "green"
        elif total >= 70:
            label = "Solid"
            color = "green"
        elif total >= 55:
            label = "Mixed"
            color = "yellow"
        elif total >= 40:
            label = "Concerning"
            color = "orange"
        else:
            label = "Critical gaps"
            color = "red"

        return {
            "total_score": total,
            "label": label,
            "color": color,
            "breakdown": {
                "technical": technical_score,
                "execution": execution_score,
                "market": market_score,
                "risk_adjusted": risk_adjusted_score,
            },
            "reasoning": reasoning,
        }
    except Exception as e:
        return {"error": str(e), "status": "failed"}


def generate_investor_brief(
    product_name: str,
    one_line_pitch: str,
    market_size: str,
    top_competitor: str,
    market_gap: str,
    founder_fit_score: int,
    founder_fit_summary: str,
    top_risk: str,
    top_risk_mitigation: str,
    core_features: list,
    build_time_weeks: int,
    verdict: str,
    verdict_reason: str,
    realistic_path_summary: str,
) -> dict:
    """
    Generate the final investor-style brief that summarizes everything.
    Call this as the very last step after all other agents have completed.

    Args:
        product_name: The product name from the MVP plan
        one_line_pitch: Under-15-word pitch
        market_size: TAM estimate (e.g. "$4.2B")
        top_competitor: Name of main competitor
        market_gap: The gap this idea fills
        founder_fit_score: The 0-100 score
        founder_fit_summary: 1 sentence summary of the score
        top_risk: The #1 risk from the critic
        top_risk_mitigation: How to address it
        core_features: List of 3 MVP features
        build_time_weeks: Weeks to build MVP
        verdict: PURSUE, PIVOT, or PAUSE
        verdict_reason: 2-3 sentence verdict explanation
        realistic_path_summary: Key milestones of the realistic path

    Returns:
        Formatted investor brief text
    """
    try:
        features_text = "\n".join([f"  • {f}" for f in core_features])
        brief = f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INVESTOR BRIEF — {product_name.upper()}
Generated by Future Founder Twin
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

IDEA
{one_line_pitch}

MARKET
{market_size} TAM | Gap: {market_gap}
Primary competitor: {top_competitor}

FOUNDER FIT: {founder_fit_score}/100
{founder_fit_summary}

MVP FEATURES
{features_text}
Build time: {build_time_weeks} weeks

TOP RISK
{top_risk}
Mitigation: {top_risk_mitigation}

REALISTIC PATH
{realistic_path_summary}

VERDICT: {verdict}
{verdict_reason}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
""".strip()

        return {"brief": brief, "verdict": verdict, "score": founder_fit_score}
    except Exception as e:
        return {"error": str(e), "status": "failed"}
